
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

//        make the phone call
//        Mobile mobile = new Iphone("1234556");
//        mobile.makeACall();

        // show the phone information
        Iphone iphone = new Iphone("iphone", "black", "iphone");
        iphone.showTheInfo();


        Andriod andriod = new Andriod("HuaWei", "black", "HuaWei");
        andriod.showTheInfo();

        // iphone change Andriod
        Person person = new Person(new Iphone("My message is to long.............."));
        person.makeACall();
        person.changeMyPhone(new Andriod("HuaWei", "black", "HuaWei"));

        // Andriod change iphone
        Person person1 = new Person(new Andriod("This is my message."));
        person1.makeACall();
        person1.changeMyPhone(new Iphone("iphone", "black", "iphone"));

    }
}
